# _____   _
# |  __ \ | |
# | |__)  | |  __ _ ___ _ __ ___
# |  ___/ | | / _` / __| '_ ` _ \
# | |     | |  (_| \__ \ | | | | |
# |_|     |_| \__,_|___/_| |_| |_|

# Version: @version@
# You can use that placehoders:
# Minecraft:
# - %player.name% | %player.head2d% | %player.head3d%
# Discord:
# - %member.nickname% | %member.id%
# Anything:
# - %message%

# Bot settings
bot:
  token: ""
#   Allowed:
#   DEFAULT, LISTENING, STREAMING, WATCHING
  activity-type: "DEFAULT"
  activity: ""

webhook:
  url: "" # Webhook URL
  nickname: "%player.name%"
  avatar-url: "%player.head2d%" # Use %player.head2d% / %player.head3d% or any image

discord:
  server: "" # Discord server ID
  channel: "" # Discord channel ID
  send-type: "BOT" # WEBHOOK or BOT

# Message Formatting
message-format:
#  To Discord
  bot: "%player.name%: %message%"
  webhook: "%message%"
#  To Minecraft
  minecraft: "&7<%member.nickname%> %message%"

config-version: 1  #Do not change this value.